//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1262228_Arosh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classess()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int ClassId { get; set; }
        public string Name { get; set; }
        public Nullable<int> SeatCapacity { get; set; }
        public string Section { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> RoomNo { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
